### ISSUE TITLE
Evaluate Technologies

### ISSUE THREAD

**Issue by dverhas** [FrozenSquirrels/polyglot#2]
Technologies and languages are "architectural decisions" (difficult to change later).

Known constraints:
 * Python
 * Python anywhere
 * SQL Lite
 * bottle.py

Task: Determine what other tools we will need for site development
Done when tools are finalized and what/why we need each tool.

**Comment by nathanbreitsch** [comment]
There are three common tasks in web development that I think call for additional technologies:

Object-relational mapping: convert between python objects and database records
   why we need it: schema defined in python, automated database setup, no parsing results or    constructing sql strings.
   suggestion: sqlAlchemy
Declarative Data Binding: synchronize ui with javascript data
   why we need it: want to do templates on client side (not server)
   suggestion: angular, knockout, ember, or react
HTML Layout: make pages look nice with minimum effort
  suggestion: bootstrap

**Comment by rsuhaibani** [comment]
Just to mention we may need MongoDB for storing the data as plan B.
In addition to that, Sublime Text editor for writing the python code.

**Comment by nathanbreitsch** [comment]
I went with knockout.js for data-binding, sqlAlchemy for ORM, and sqlite3 for db. 
Lets keep mongodb in mind for possible transition.  In sql, we will need a different table for each prompt type.  In mongo, all prompts can be stored in one collection (but that means the code must have type separation logic).  At this point it is unclear to me whether mongo or sqlite is better for what we're doing.  But sqlite is easy, on pythonanywhere by default, and apparently required by delozier. (but we can use both for unrelated subsets of the data)

We can all use different editors.  I'm using Atom because I want to spend my $70 on food and gasoline.

To learn knockout: http://learn.knockoutjs.com/
To learn sqlAlchemy: https://www.udacity.com/course/ud088
      (lesson 1: working with CRUD)

**Comment by rsuhaibani** [comment]
@nathanbreitsch Thanks for this clarification.
